# Generated by Django 5.2.8 on 2025-12-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nome',), 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('nome',)},
        ),
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['cidade', 'uf'], name='idx_cidade_uf'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['id', 'slug'], name='main_produt_id_5f3016_idx'),
        ),
    ]
