# Generated by Django 6.0 on 2025-12-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_categoria_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
    ]
